const lang1 = {
    'en': {
        'burger-about-me': 'About me',
        'burger-experience': 'Experience',
        'burger-education': 'Education',
        'burger-projects': 'Projects',
        'burger-skills': 'Skills',
        'burger-languages': 'Languages',
        'burger-sample-code': 'Sample code',

        'header-about-me': 'About me',
        'header-experience': 'Experience',
        'header-education': 'Education',
        'header-projects': 'Projects',
        'header-skills': 'Skills',
        'header-languages': 'Languages',
        'header-sample-code': 'Sample code',
        'about-me-id': 'About me',
        'experience-id': 'Experience',
        'education-id': 'Education',
        'projects-id': 'Projects',
        'skills-id': 'Skills',
        'languages-id': 'Languages',
        'sample-code-id': 'Sample code',
        'title-h1-name': 'Daria',
        'title-h1-fam': 'Teplovodskaya',
        'proffession-name-id': 'Junior Frontend developer',
        'about-me-paragraph-1': 'Hello! My name is Daria, I am a beginner front-end developer. I am currently studying at Rolling Scopes School.',
        'about-me-paragraph-2': 'In the future, I want to become a real professional in order to quickly and efficiently do my job. I am very responsible and accept constructive criticism calmly.',
        'about-me-paragraph-3': 'My goal is to make this world a better place with new technologies. My priority is to create the perfect apps for user comfort. My skills are not that good right now, but I study and practice a lot.',
        'education-span-1': 'General secondary education',
        'education-span-2': 'Technological Institute',
        'experience-span-1': 'Passing the Rolling Scopes School course «Javascript/frontend»',
        'experience-span-2': 'Self-study and practice on pet-projects',
        'project-card-1-p': 'Landing page',
        'project-card-2-p': 'Landing page',
        'project-card-3-p': 'Custom video player',
        'pr-card-1-hover-description': 'Landing page with elements of an online store.',
        'pr-card-2-hover-description': 'Landing page for the museum',
        'pr-card-3-hover-description': 'Custom video player-slider',
        'pr-card-hover-tecnologies-1': 'Technologies that were applied:',
        'pr-card-hover-tecnologies-2': 'Technologies that were applied:',
        'pr-card-hover-tecnologies-3': 'Technologies that were applied:',
        'more-project': 'more work in progress',
        'lang-eng': 'English',
        'lang-ru': 'Russian',
        'my-github': 'My GitHub',
        'frontend-course': 'Frontend course',
        'design': 'Design by Daria Teplovodskaya',
    },

    'ru': {
        'burger-about-me': 'Обо мне',
        'burger-experience': 'Опыт',
        'burger-education': 'Образование',
        'burger-projects': 'Проекты',
        'burger-skills': 'Навыки',
        'burger-languages': 'Языки',
        'burger-sample-code': 'Пример кода',

        'header-about-me': 'Обо мне',
        'header-experience': 'Опыт',
        'header-education': 'Образование',
        'header-projects': 'Проекты',
        'header-skills': 'Навыки',
        'header-languages': 'Языки',
        'header-sample-code': 'Пример кода',
        'about-me-id': 'Обо мне',
        'experience-id': 'Опыт',
        'education-id': 'Образование',
        'projects-id': 'Проекты',
        'skills-id': 'Навыки',
        'languages-id': 'Языки',
        'sample-code-id': 'Пример кода',
        'title-h1-name': 'Дарья',
        'title-h1-fam': 'Тепловодская',
        'proffession-name-id': 'Junior Frontend разработчик',
        'about-me-paragraph-1': 'Привет! Меня зовут Дарья, и я начинающий frontend разработчик.',
        'about-me-paragraph-2': 'В будущем я хочу стать настоящим профессионалом, чтобы быстро и качественно выполнять свою работу. Я ответственная и спокойно отношусь к конструктивной критике.',
        'about-me-paragraph-3': 'Моя цель - сделать этот мир лучше с помощью новых технологий. Моя приоритетная задача - создавать идеальные приложения для комфорта пользователя. Сейчас мои навыки не так хороши, но я много учусь и практикуюсь.',
        'education-span-1': 'Общее среднее образование',
        'education-span-2': 'Технологический институт',
        'experience-span-1': 'Обучение на  курсе Rolling Scopes School «Javascript/frontend»',
        'experience-span-2': 'Самообучение на pet-projects',
        'project-card-1-p': 'Лендинг',
        'project-card-2-p': 'Лендинг',
        'project-card-3-p': 'Кастомный видео-плеер',
        'pr-card-1-hover-description': 'Лендинг страница с элементами интернет-магазина.',
        'pr-card-2-hover-description': 'Лендинг страница для музея',
        'pr-card-3-hover-description': 'Кастомный видеоплеер слайдер',
        'pr-card-hover-tecnologies-1': 'Примененные технологии:',
        'pr-card-hover-tecnologies-2': 'Примененные технологии:',
        'pr-card-hover-tecnologies-3': 'Примененные технологии:',
        'more-project': 'проекты в процессе',
        'lang-eng': 'Английский',
        'lang-ru': 'Русский',
        'my-github': 'Мой GitHub',
        'frontend-course': 'Frontend курс',
        'design': 'Дизайн Дарьи Тепловодской',
    }

}

export default lang1;